# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

font_size                 15.0
font_family               Hack Nerd Font Mono
bold_font                 Hack Nerd Font Mono Bold
italic_font               Hack Nerd Font Mono Italic
bold_italic_font          Hack Nerd Font Mono Bold Italic
adjust_line_height        110%
disable_ligatures         always
text_composition_strategy 2

# window
initial_window_width  110c
initial_window_height 32c
hide_window_decorations        titlebar-only
# linux_display_server           x11
window_padding_width           15
background_opacity             0.96
remember_window_size           no

# Linux 上 background_blur 大概率没啥用，先注释
# background_blur                64

# tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted

# macOS only
# macos_option_as_alt yes

# Linux / Windows-style key mapping
map ctrl+s        send_text all \e:w\r
map ctrl+p        send_text all :Telescope\ find_files\r
map ctrl+shift+f  send_text all :Telescope\ live_grep\r
map ctrl+b        send_text all :Neotree\ toggle\r

# tmux key mapping
map alt+1 combine : send_key ctrl+space : send_key 1
map alt+2 combine : send_key ctrl+space : send_key 2
map alt+3 combine : send_key ctrl+space : send_key 3
map alt+4 combine : send_key ctrl+space : send_key 4
map alt+5 combine : send_key ctrl+space : send_key 5
map alt+6 combine : send_key ctrl+space : send_key 6
map alt+7 combine : send_key ctrl+space : send_key 7
map alt+8 combine : send_key ctrl+space : send_key 8
map alt+9 combine : send_key ctrl+space : send_key 9

# cursor & misc
cursor_blink_interval 0
detect_urls no
mouse_hide_wait 0.5

# Pane / Split management
map ctrl+shift+enter launch --location=vsplit --cwd=current
map ctrl+shift+]     launch --location=hsplit --cwd=current

# pane navigation
map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right

# resize pane
map ctrl+shift+alt+h resize_window narrower
map ctrl+shift+alt+l resize_window wider
map ctrl+shift+alt+k resize_window taller
map ctrl+shift+alt+j resize_window shorter

# close pane
map ctrl+shift+w     close_window
