### --- prefix 设置（推荐） ---
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# set -g default-terminal "tmux-256color"

# 告诉 tmux：kitty 终端支持真彩
# tmux 3.2+ 推荐：
set -as terminal-features 'xterm-kitty:RGB'
# 兼容一些环境：
set -ga terminal-overrides ',xterm-kitty:RGB'

### --- 插件 ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


### --- resurrect / continuum ---
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'


### --- 分屏（更直觉） ---
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"


### --- 重新加载配置 ---
unbind r
bind r source-file ~/.tmux.conf


### --- pane 尺寸调整（vim 风格） ---
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
# bind kill window to w
bind w kill-window

### --- 基础设置 ---
set -g mouse on
set -g mode-keys vi
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on


### --- copy mode (vi) ---
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection


### --- TPM 初始化（必须放底部） ---
run '~/.tmux/plugins/tpm/tpm'
